### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by denny64** [pyronlaboratory/heroku-integrated-firefox-geckodriver#22]
Hi - Just wondering if this is still being maintained? Happy to take over and merge with https://github.com/digitalcircuits/heroku-integrated-firefox-geckodriver

Would be nice to also support Heroku-20

**Comment by pyronlaboratory** [comment]
Hi @denny64,

The repository is still being maintained through this account, though a helping pull request would be much appreciated.

Since the release of `Heroku-20`, I've been evaluating the security vulnerabilities in the current code base in a private branch. Although new developers, who are starting now are using `Heroku-20` since its the default one, majority users of this repository are using the build pack for their legacy applications, which were built on the previous stable stack.

In the next release of the build pack, plans are to add support for the latest stack, and deprecate the discontinued stack.

That being said, if you've a working source, I'd be happy to evaluate your code base and merge with the repository.

Cheers mate!
